name: 릴리즈 준비

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git 설정
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 최신 버전 조회
        id: get_version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: 릴리즈 브랜치 및 태그 생성
        run: |
          # 현재 날짜와 시간으로 버전 생성
          NEXT_VERSION=$(date +'%Y.%m.%d-%H%M')
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_OUTPUT

          # release 브랜치 생성 (형식 변경)
          git checkout -b releases/version-${NEXT_VERSION}

          # 버전 태그 생성
          git tag v${NEXT_VERSION}

          # 변경사항 push
          git push origin releases/version-${NEXT_VERSION}
          git push origin v${NEXT_VERSION}
